apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydjangoapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydjangoapp
  template:
    metadata:
      labels:
        app: mydjangoapp
    spec:
      containers:
      - name: mydjangoapp
        image: ajayrajsingh31/mydjangoapp:latest
        ports:
        - containerPort: 8000
