apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydjangoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydjangoapp
  template:
    metadata:
      labels:
        app: mydjangoapp
    spec:
      containers:
      - name: mydjangoapp
        image: ajayrajsingh31/django
        ports:
        - containerPort: 8000
